name: VanishPlugin
version: 1.0.0
author: Sami200IQ
main: net.samidh.vanishplugin.VanishPlugin
commands:
  vanish:
    permission: vanish.use
    permission-message: You don't have the permission to do that